# Environment where the service is running
env: local
  
service:
  protocol: "HTTPS"
  port: "443"
  path:
    contact: "/api/contact"
    phone: "/api/phone"
    address: "/api/address"
    email: "/api/email"
    tribalenrollment: "/api/tribalenrollment"
    account: "/api/account"
    balance: "/api/balance"
    agencyregion: "/api/agencyregion"
    disbursement: "/api/disbursement"