# The RAML API and autodiscovery
api:  
  group: "${restconnector.api.spec.group}"
  artifact: "${restconnector.api.spec.artifact}"
  version: "${restconnector.api.spec.version}"
  spec: "resource::${api.group}:${api.artifact}:${api.version}:raml:zip:api.raml"
  id: "0"

# Environment where the service is running
env: local

# Maximum number of records read from SSOT
maxrecords: "2000"

# Anypoint platform for notifications
notification:
  platform: "https://gov.anypoint.mulesoft.com"
  message:
    mainetl: "The main ETL process started sucessfully"


service:
  protocol: "HTTPS"
  port: "443"
  path:
    contact: "/api/contact"
    address: "/api/address"
    email: "/api/email"
    phone: "/api/phone"
    account: "/api/account"
    accountudf: "/api/accountudf"
    agencyregion: "/api/agencyregion"
    balance: "/api/balance"
    disbursement: "/api/disbursement"