# Environment where the service is running
env: local

# Maximum number of records read from SSOT
maxrecords: "2000"

service:
  protocol: "HTTPS"
  port: "443"
  path:
    contact: "/api/contact"
    address: "/api/address"
    phone: "/api/phone"
    account: "/api/account"
    accountudf: "/api/accountudf"
    agencyregion: "/api/agencyregion"
    balance: "/api/balance"
    disbursement: "/api/disbursement"