name: Build v2
 
on:
  push:
    branches: [ "main" ]
  pull_request: 

jobs: 
  buildtest:
    uses: btfacrm/common-devops/.github/workflows/mule-secretsmgm.yml@main
    secrets: inherit
    
    # Needed by the Unit Test Action
    permissions:
      contents: write
      issues: write
      checks: write
