name: Deployment
 
on:
  issues:
    #types: [opened]

jobs: 
  Deployment:
    uses: btfacrm/common-devops/.github/workflows/mule-deployment.yml@main
    secrets: inherit

    # Needed by the Unit Test Action
    permissions:
      contents: write
      issues: write
      checks: write
